baseURL = "https://ittechnetworkk.github.io/"
languageCode = "en-us"
title = "ittechnetworkk"
theme = "cactus"
copyright = "ittechnetworkk"

# ignoreLogs
ignoreLogs = ['warning-goldmark-raw-html']

# Enable categories taxonomy
[taxonomies]
  category = "categories"
  tag = "tags"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Walkthroughs"
url = "/walkthroughs"
weight = 3

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 4

[[menu.main]]
name = "Tools"
url = "/tools/"
weight = 5
identifier = "tools"

[[menu.main]]
name = "What is my IP?"
url = "/what-is-my-ip"
parent = "tools"
weight = 1

[[menu.main]]
name = "Subnet Calculator"
url = "/subnet-calculator"
parent = "tools"
weight = 2

[[menu.main]]
name = "Cisco IOS Config Generator"
url = "/cisco-ios-config"
parent = "tools"
weight = 3

[[menu.main]]
name = "Junos Config Generator"
url = "/junos-config"
parent = "tools"
weight = 4

[[menu.main]]
name = "Resources"
url = "/resources"
weight = 6

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 7

[[menu.main]]
name = "Library"
url = "/library"
weight = 8

[[menu.main]]
name = "About"
url = "/about"
weight = 9

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  colortheme = "dark"
  showAllPostsArchive = true 
  description = "Hi, I'm Soner, and this is my personal blog where I share insights, guides, and articles on various tech topics, including Networking, Linux, Windows, Virtualization, Firewalls, IoT, and more. I'm constantly learning and exploring new technologies, and this blog is where I document my journey. "
  mainSection = "posts"
  showAllPostsOnHomePage = true
  postsOnHomePage = 5
  tagsOverview = true
  showProjectsList = true
  projectsUrl = "https://ittechnetworkk.github.io/"
  
  # Custom logo - using Font Awesome military badge icon
  logo = "fas fa-medal"
  
  # Custom CSS files
  css = ["css/custom.css"]

  # Date format
  dateFormat = "2006-01-02"

  # Post page settings
  show_updated = true
  showReadTime = true

  [[params.social]]
    name = "github"
    link = "https://github.com/ssnrshnn"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/soner-sahin-943262174/"

  [[params.social]]
    name = "twitter"
    link = "https://x.com/sonersahin1881"
    
  [[params.social]]
    name = "email"
    link = "ittechnetworkk@gmail.com"

