baseURL = "https://ittechnetworkk.github.io/"
languageCode = "en-us"
title = "ittechnetworkk"
theme = "cactus"
copyright = "ittechnetworkk"

# Enable categories taxonomy
[taxonomies]
  category = "categories"
  tag = "tags"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 5

[[menu.main]]
name = "About"
url = "/about"
weight = 6

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  colortheme = "dark"
  showAllPostsArchive = true 
  description = "Hello, I'm Soner from Turkey. I prefer working with the CLI rather than GUI. On this site, I share my expertise in various technologies, insights into newly learned tools, as well as details of the projects I have completed and those I plan to undertake. I run this blog with the motivation to learn, have fun, and help others along the way."
  mainSection = "posts"
  showAllPostsOnHomePage = true
  postsOnHomePage = 5
  tagsOverview = true
  showProjectsList = true
  projectsUrl = "https://ittechnetworkk.github.io/"

  # Date format
  dateFormat = "2006-01-02"

  # Post page settings
  show_updated = true
  showReadTime = true

  [[params.social]]
    name = "github"
    link = "https://github.com/ssnrshnn"

  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/soner-sahin-943262174/"

  [[params.social]]
    name = "twitter"
    link = "https://x.com/sonersahin1881"
    
  [[params.social]]
    name = "email"
    link = "ittechnetworkk@gmail.com"

